### ISSUE TITLE
Size of universe

### ISSUE THREAD

**Issue by petrohi** [gheorghina/GameOfLife#1]
I understand that size of universe is limited to 40x40 cells and cells beyond this are always dead. (Correct me if I am wrong.)

Can you change implementation to support large (2^64x2^64) sparse universe? In the case of glider gun such universe will grow over time as more gliders get introduced. Also such universe should wrap on itself in both dimensions.

**Comment by gheorghina** [comment]
Yes. You are right, you can initialize the grid to a larger value (code change)..but, as it is now, it does not support the glider load accordingly.

I have a better ideea on how to optimize a bit the algorithm, but I have two questions first :

1. Shall the universe grow dynamically up to a certain larger size(2^64), or is it ok to support different static introduced initial sizes with the corresponding glider load?

2. Shall the application allow to introduce multiple gliders at the same position , or at a dynamic introduced one, based on the universe size at that time? 

Then..there is the web limitation. I don't know right know how much it can take..but we can try to see..

**Comment by petrohi** [comment]
Universe should grow dynamically. I suggest to try not thinking in terms of X by Y grid, but instead in terms of sparse data structures containing just live cells ;-)

Gliders get introduced from the gun and fly away constantly adding live cells to the universe. This will be slowing down iterations of the algorithm. Think how to make it slow down less.

**Comment by gheorghina** [comment]
Yep, this was the approach I was thinking off. 
I already did parts of the changes ( on a different branch) - at least to be able to set an initial size from the UI, and then I adjusted the gun loading to work on any universe size - by saving/loading a slimmer version (only the living cells)

I will think how to also make it grow dynamically, and slow down less ...

**Comment by petrohi** [comment]
I looked at new implementation and have two comments. 

Performing computation on the entire grid from _[0, 0]_ to _[max(alive.x), max(alive.y)]_ may become very expensive as gliders continue to fly out--you'd iterate over mostly empty space. Can this be improved?

Cell lookup using `indexOfPair` has O(N) complexity, which combined with `evolve` iteration gives up O(N^2). Can this be improved?

**Comment by gheorghina** [comment]
At a quick glance, I would try to cover both at once by just iterating over the alive old generation cells.
(I would try to remove both the need to calculate the index and the need to go over the entire universe)

This way, I would also already have the index in place - but it might not be need, since the calculations would be a bit different(i have to see exactly).

The algorithm then would be a bit more complex for calculating the new states:
- for the alive cells: -> i would need to find the alive neighbors cells, and the rest that are not in the generation array,  they will be considered dead ( paying attention to the margins)
- then one more step would be to identify mathematically (with a reverse logic) which of the dead missing from the array neighbors shall be brought to life(also by paying attention to the margins) 

... but it can be done.

The current solution, is just lazier, since the calculations are simpler.

**Comment by gheorghina** [comment]
So then, the next approach would be to reduce the lookup area - only around the living cells, and compute only around those ... this would lead to more smaller square areas... for which I will compute the evolution of the cells.

The next two day I will be caught in a workshop, i will try it in the weekend.

**Comment by petrohi** [comment]
Sounds good.

**Comment by gheorghina** [comment]
I will close the issues.  in case something new appears, I will create a new branch.
